### ISSUE TITLE
Asset optimization

### ISSUE THREAD

**Issue by mstijak** [Runjuu/html-inline-css-webpack-plugin#1]
The plugin works well, except for the fact that it includes CSS before optimizations are made.

I'm using `OptimizeCSSAssetsPlugin`, but that doesn't seem to have an effect on the result. 
Is there a way to include optimized CSS?

**Comment by Runjuu** [comment]
Thanks for reporting this bug which now is fixed in latest release 🍻

**Comment by mstijak** [comment]
It works. Thanks!
