### ISSUE TITLE
removeLinkTag should replace all occurences of the css chunk

### ISSUE THREAD

**Issue by m5nv** [Runjuu/html-inline-css-webpack-plugin#10]
I hit on this while trying to get css preload to work in chrome and load normally in other browsers as suggested in a comment at [SO](https://stackoverflow.com/questions/45321043/preload-css-file-not-supported-on-firefox-and-safari-mac).

The bug can be traced to [this line](https://github.com/Runjuu/html-inline-css-webpack-plugin/blob/master/src/index.ts#L46).

The solution is to pass 'gi' parameter to RegExp object to find and 'remove' all occurrences of the chunk that needs to be inlined.

I fixed it locally and works for me. Cheers!

**Comment by Runjuu** [comment]
Yes, we should. But seems that `i` is unnecessary in this case. 🤔️ Did I miss something?

**Comment by m5nv** [comment]
> Yes, we should. But seems that `i` is unnecessary in this case. thinking Did I miss something?

Doesn't hurt. Some folks like to use weird case for their tags. The html spec allows tag names and attribute names to be case-insensitive (at least the browsers don't seem to have issue with mixed case).  

HTH.

**Comment by m5nv** [comment]
> > Yes, we should. But seems that `i` is unnecessary in this case. thinking Did I miss something?
> 
> Doesn't hurt. Some folks like to use weird case for their tags. The html spec allows tag names and attribute names to be case-insensitive (at least the browsers don't seem to have issue with mixed case).
> 
> HTH.

@Runjuu Any plans on doing a release with the fix any time soon? Thanks!

**Comment by Runjuu** [comment]
@m5nv I'm sorry to have you keep waiting, 1.6.0 now is released.
