### ISSUE TITLE
filter function must return 'true' for css file as well as the output html file

### ISSUE THREAD

**Issue by aKzenT** [Runjuu/html-inline-css-webpack-plugin#16]
If I understand the code correctly, the filter function is not only called for the CSS files to decide if they should be inlined or not, but also for the target .html-file in which the styles should be injected.

I don't think this is very intuitive and at the very least it should be mentioned in the documentation. I had to debug through the plugin to find out, why my CSS does not get inlined.

**Comment by aKzenT** [comment]
Another small gotcha is that the example `target` is using a HTML-comment which is removed by default by the html-webpack-plugin in production mode (https://github.com/jantimon/html-webpack-plugin#minification )

**Comment by Runjuu** [comment]
Hi @aKzenT , I have updated REAMED according to your advice. Let me know if there is any problem. 😄

**Comment by aKzenT** [comment]
Thanks!
