### ISSUE TITLE
Specify extracted CSS files to make internal 

### ISSUE THREAD

**Issue by josephkeiser** [Runjuu/html-inline-css-webpack-plugin#2]
Is there any way to specify a file (or files) to make internal, rather than processing all files that the mini-css-extract-plugin creates? Something like the [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin#use-case-internalize-critical-css-with-all-other-css-in-an-external-file) offers?

**Comment by Runjuu** [comment]
Sounds great, now is supported in the latest release. check [this](https://github.com/Runjuu/html-inline-css-webpack-plugin/blob/master/README.md#filteroptional)

**Comment by josephkeiser** [comment]
I haven’t been able to test this out, but it looks great. Thanks.
