### ISSUE TITLE
About this plugins refreshed question

### ISSUE THREAD

**Issue by Octopus912** [Runjuu/html-inline-css-webpack-plugin#30]
when i refresh , the <style></style> always add one

**Comment by Runjuu** [comment]
Hi @Octopus912 , Sorry for the delayed response. Can you provide a minimal demo to reproduce the issue?

**Comment by idudinov** [comment]
@Runjuu  I think I can elaborate on that issue.

I'm using the latest versions of `webpack`, `html-webpack-plugin`, `mini-css-extract-plugin` and `html-inline-css-webpack-plugin` itself.

While working with webpack dev server, each time CSS re-compiles, this plugin increments output and breaks output CSS content. This can be tracked by logging `style` while using `styleTagFactory` config option.

Let's say I have:

```javascript
styleTagFactory({ style }) {
  console.log(' ============== styleTagFactory ', style);
  return `<style type="text/css">
/* begin */
${style}
/* end */
</style>`;
},
```

during the initial build it will output just as expected:

```html
<style type="text/css">
/* begin */
.my-class {
  opacity: 1; }
/* end */
</style>
```

then if I change CSS (set `opacity` to 0.5), the second time output will be:

```html
<style type="text/css"><style type="text/css">
/* begin */
.my-class {
  opacity: 0.5; }
/* end */
</style>
/* begin */
.my-class {
  opacity: 1; }
/* end */
</style>
```

and in the logs there will be 2 entries (old and new):

```
============== styleTagFactory: .my-class {
  opacity: 1; }

 ============== styleTagFactory: .my-class {
  opacity: 0.5; }
```

so it looks like the plugin apply twice. And then, if I try to make another change, I will see 3 passes and so on.

Hope there is some workaround or possible quick fix!

**Comment by Runjuu** [comment]
@idudinov Huge thanks for providing reproduction steps! I think I’ve found the cause of the problem and release an alpha version `1.11.0-alpha.1` for testing. Let me know if there are any problems.

**Comment by idudinov** [comment]
@Runjuu yep, that worked!! thanks a lot!
