### ISSUE TITLE
html-webpack-plugin 5 peer dep

### ISSUE THREAD

**Issue by daniele-orlando** [Runjuu/html-inline-css-webpack-plugin#33]
Please, can you update the `package.json` definition to support _html-webpack-plugin_ **5**?

```
"peerDependencies": {
    "html-webpack-plugin": "^3 || ^4 || ^5"
},
```

Otherwise:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app@1.0.20210204-b
npm ERR! Found: html-webpack-plugin@5.0.0
npm ERR! node_modules/html-webpack-plugin
npm ERR!   html-webpack-plugin@"5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer html-webpack-plugin@"^3.0.0 || ^4.0.0" from html-inline-css-webpack-plugin@1.10.0
npm ERR! node_modules/html-inline-css-webpack-plugin
npm ERR!   html-inline-css-webpack-plugin@"*" from the root project
```

Thank you.

**Comment by daniele-orlando** [comment]
As additional detail. Using `filter` option, nothing is emitted inside the HTML file, eve if the filter does match.

**Comment by Runjuu** [comment]
Hi @daniele-orlando , I've updated the peer dependencies and released a new version to NPM. For the `filter` issue, can you provide a minimal demo to reproduce that?

**Comment by groseler** [comment]
> As additional detail: using `filter` option, nothing is injected inside the HTML file, even if the filter does match; but the matched files are deleted from the filesystem.

@Runjuu I'm experiencing the same problem with the following example:

```
new HTMLInlineCSSWebpackPlugin({
        filter: (fileName) => {
            return fileName.includes('critical')
        },
        styleTagFactory: ({ style }) => {
            return `<style type="text/css">${style}</style>`;
        },
        leaveCSSFile: true,
        replace: {
            removeTarget: true,
            target: '<!-- inline_css_plugin -->',
        },
    }),
```

The weird part is that if I set the filter for the negative, the other files are included inline:

```
return !fileName.includes('critical')
```

**Comment by groseler** [comment]
**UPDATE**: I went to try other versions and in the 1.3.2 is the last one working. Hope it helps.
