### ISSUE TITLE
CSS files are deleted when using together with CopyWebpackPlugin

### ISSUE THREAD

**Issue by creage** [Runjuu/html-inline-css-webpack-plugin#39]
In my webpack config I have my **main** entry with HTML+CSS, and I want this CSS to be injected. I use simple
```js
new HtmlInlineCSSWebpackPlugin()
```
for doing this, and it works fine.

I also have a [CopyWebpackPlugin](https://github.com/webpack-contrib/copy-webpack-plugin), which copies some third party lib, which includes HTML+CSS files in its assets. 

These CSS files are removed when being copied. They are not removed if I use `leaveCSSFile: true`, but then the CSS file from **main** entry is not removed either.

I wonder why does this plugin deal with files from other plugin? But even if it does - I would expect these CSS get injected correctly in all HTML+CSS pairs it deals with. Currently it only REMOVES all of CSS files, without injecting them.

**Comment by Runjuu** [comment]
Hi @creage, Sorry for the delayed response. Can you provide a minimal demo to reproduce the issue?

**Comment by creage** [comment]
@Runjuu here you go [html-inline-css-webpack-plugin-broken](https://github.com/creage/html-inline-css-webpack-plugin-broken)

```js
npm i
npm run build
```
Then check contents of `dest/vendor` folder. It should have both `index.html` and `index.css`, but has `.html` file only.

**Comment by creage** [comment]
BTW, filtering on assets also works 😃 
```js
new HtmlInlineCSSWebpackPlugin({
	filter(name) {
		// don't mess the vendor styles!
		return !name.includes('vendor');
	}
})
```

**Comment by creage** [comment]
Any progress on this issue?

**Comment by Runjuu** [comment]
@creage There’s been no progress so far 😢
