### ISSUE TITLE
Failed to inline CSS files by `options.filter`

### ISSUE THREAD

**Issue by aicest** [Runjuu/html-inline-css-webpack-plugin#43]
Reproduce 👉 [html-inline-css-webpack-plugin-demo.zip](https://github.com/Runjuu/html-inline-css-webpack-plugin/files/6595508/html-inline-css-webpack-plugin-demo.zip)

**Comment by immuzov** [comment]
I got same problem.

**Comment by Runjuu** [comment]
Hi @aicest, Sorry for the delayed response. The reason it failed was that `index.html` was also filtered out. You can update the filter to something like `/loading|html/.test(fileName)` to fix it.
